wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/discrete_SQL/discrete_SQL.py
    framework: huggingface
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1706909767.862967
    t:
      1:
      - 1
      - 2
      - 3
      - 55
      2:
      - 1
      - 2
      - 3
      - 11
      - 49
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.8.5
      5: 0.13.11
      8:
      - 5
a_bins:
  desc: null
  value: 20
alpha:
  desc: null
  value: 1.0
autotune:
  desc: null
  value: false
batch_size:
  desc: null
  value: 256
buffer_size:
  desc: null
  value: 1000000
capture_video:
  desc: null
  value: false
cuda:
  desc: null
  value: true
env_id:
  desc: null
  value: Hopper-v4
exp_name:
  desc: null
  value: discrete_SQL
gamma:
  desc: null
  value: 0.99
learning_starts:
  desc: null
  value: 5000.0
nhead:
  desc: null
  value: 2
num_layers:
  desc: null
  value: 4
policy_frequency:
  desc: null
  value: 2
q_lr:
  desc: null
  value: 0.001
seed:
  desc: null
  value: 1
target_network_frequency:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.005
torch_deterministic:
  desc: null
  value: true
total_timesteps:
  desc: null
  value: 1000000
track:
  desc: null
  value: true
wandb_entity:
  desc: null
  value: swish
wandb_project_name:
  desc: null
  value: advantage-diffusion
